version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Use the Dockerfile you previously created
    ports:
      - "5000:5000"  # Map the Flask app's port to the host
    networks:
      - app_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Map port 80 of the host to Nginx's port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount Nginx configuration
    depends_on:
      - web
    networks:
      - app_net

networks:
  app_net:
